"""init

Revision ID: 36c80f82d77c
Revises: 
Create Date: 2026-04-01 03:28:21.384519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c80f82d77c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_rating'), 'problems', ['rating'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('cf_handle', sa.String(length=64), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cf_handle'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_users_cf_handle'), 'users', ['cf_handle'], unique=True)
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_index(op.f('ix_users_cf_handle'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problems_rating'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
